' Purpose: Rename selected sketch feature as "ETCH"

' Precondition: Have a sketch feature selected

' Postcondition: Selected sketch feature will be named "ETCH"

' Setup

Option Explicit
Sub main()
    Dim swApp As SldWorks.SldWorks
    Dim swModel As SldWorks.ModelDoc2
    Dim swSketch As SldWorks.Sketch
    Dim swFeat As SldWorks.Feature
    Set swApp = Application.SldWorks
    Set swModel = swApp.ActiveDoc
    
    ' Get the open sketch
    Set swSketch = swModel.GetActiveSketch2
    Set swFeat = swSketch
    
    ' Change the name of the open sketch
    swFeat.Name = "ETCH"
    
End Sub
